import Head from 'next/head'
import Image from 'next/image'
import Banner from '../Components/Banner'
import CardActivity from '../Components/CardActivity'
import Footer from '../Components/Footer'
import styles from '../styles/Home.module.css'

export default function Experiences() {
  return (
    <div>
      <Head>
        <title>Vives des expériences inoubliables - Community App
        </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main >
        <Banner />
        <CardActivity />
        <Footer />
      </main>

      
    </div>
  )
}
