import Head from 'next/head'
import Image from 'next/image'
import Banner from '../Components/Banner'
import CardActivity from '../Components/CardActivity'
import Footer from '../Components/Footer'
import styles from '../styles/Home.module.css'

export default function Experiences() {
  return (
    <div>
      <Head>
        <title>Vives des expériences inoubliables - Community App
        </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main >
        <Banner />

        <Accordion >
                <Card>
                    <Accordion.Toggle as={Card.Header} eventKey="0">
                    {filter === true ? 
                    <i className="bi bi-plus-square-fill me-2"></i> 
                    : <i className="bi bi-dash-square-fill me-2"></i>
                    }
                    COMMENT TÉLÉCHARGER L'APPLI COMMUNITY ?
                    </Accordion.Toggle>
                    <Accordion.Collapse eventKey="0">
                        <Card.Body>Pour télécharger Community, rendez-vous sur votre app store:
                            <Link href="/"><img src="/images/logo_apple.png" width="150" className={`${styles.social_media} me-2 mb-4`} alt="logo Google"/></Link>
                            <Link href="/"><img src="/images/logo_google.png" width="150" className={`${styles.social_media} me-2 mb-4`} alt="logo Apple"/></Link>
                        </Card.Body>
                    </Accordion.Collapse>
                </Card>
                <Card>
                    <Accordion.Toggle as={Card.Header} eventKey="1" onClick={onChangeFilter}>
                        {filter === true ? 
                        <i className="bi bi-plus-square-fill me-2"></i> 
                        : <i className="bi bi-dash-square-fill me-2"></i>
                        }
                        LES ÉVÉNEMENTS SONT-ILS RÉACTUALISÉS RÉGULIÈREMENT ?
                    </Accordion.Toggle>
                    <Accordion.Collapse eventKey="1">
                        <Card.Body>Community met à jour l’agenda de sortie dans vos villes tous les jours</Card.Body>
                    </Accordion.Collapse>
                </Card>
                <Card>
                    <Accordion.Toggle as={Card.Header} eventKey="2">
                    {filter === true ? 
                    <i className="bi bi-plus-square-fill me-2"></i> 
                    : <i className="bi bi-dash-square-fill me-2"></i>
                    }
                    COMMENT SÉLECTIONNER UNIQUEMENT LES ÉVÉNEMENTS SUCEPTIBLES DE M'INTÉRESSER ?
                    </Accordion.Toggle>
                    <Accordion.Collapse eventKey="2">
                        <Card.Body>Il vous suffit d’affiner votre rechercher en sélectionnant les catégories qui vous intéressent (sport, art, soirées etc…) et nous les sélectionnons pour vous</Card.Body>
                    </Accordion.Collapse>
                </Card>
                <Card>
                    <Accordion.Toggle as={Card.Header} eventKey="3">
                    {filter === true ? 
                    <i className="bi bi-plus-square-fill me-2"></i> 
                    : <i className="bi bi-dash-square-fill me-2"></i>
                    }
                    COMMENT ÊTRE SÛR/E QUE LES EXPÉRIENCES NE SONT PAS DES ARNAQUES ?
                    </Accordion.Toggle>
                    <Accordion.Collapse eventKey="3">
                        <Card.Body>
                        A la confirmation de votre commande, un mail vous sera envoyé avec tous les détails de la réservation 
                        (une fois que le chaperon aura accepté votre réservation).
                        Vous pourrez rentrer en contact par mail ou téléphone avec votre chaperon.
                        Le montant de l’expérience est uniquement bloqué jusqu’à la date de celle-ci, et prélevé après votre expérience. 
                        Si votre expérience a été annulé par votre chaperon, le montant vous sera re crédité sur votre compte. 
                        Community dispose par ailleurs d’une équipe dédiée qui vérifie au quotidien les chaperons avant de les valider sur la plateforme.
                        </Card.Body>
                    </Accordion.Collapse>
                </Card>
                <Card>
                    <Accordion.Toggle as={Card.Header} eventKey="4">
                    {filter === true ? 
                    <i className="bi bi-plus-square-fill me-2"></i> 
                    : <i className="bi bi-dash-square-fill me-2"></i>
                    }
                    EST-CE QUE L'APPLICATION MOBILE EST SÉCURISÉE ?
                    </Accordion.Toggle>
                    <Accordion.Collapse eventKey="4">
                        <Card.Body>Nous utilisons les toutes dernières technologies d’encryption de données, et travaillons en partenariat 
                        avec le spécaliste mondiale du paiement en ligne: Stripe.
                        Vos données bancaires sont conservées sur leurs serveurs, et sont donc en toute sécurité. 
                        Vous pouvez nous (et leur) faire confiance !</Card.Body>
                    </Accordion.Collapse>
                </Card>
                <Card>
                    <Accordion.Toggle as={Card.Header} eventKey="5">
                    {filter === true ? 
                    <i className="bi bi-plus-square-fill me-2"></i> 
                    : <i className="bi bi-dash-square-fill me-2"></i>
                    }
                    ET SI JE VEUX ANNULER UNE EXPÉRIENCE ?
                    </Accordion.Toggle>
                    <Accordion.Collapse eventKey="5">
                        <Card.Body>Vous disposez du droit d’annuler gratuitement votre expérience jusque 24h à l’avance au minimum. 
                        Au-delà, vous ne pourrez être remboursé du montant.</Card.Body>
                    </Accordion.Collapse>
                </Card>
                <Card>
                    <Accordion.Toggle as={Card.Header} eventKey="6">
                    {filter === true ? 
                    <i className="bi bi-plus-square-fill me-2"></i> 
                    : <i className="bi bi-dash-square-fill me-2"></i>
                    }
                    COMMENT SAVOIR SI J'AI DES AMIS QUI PARTICIPENT AUX ÉVÉNEMENTS ?
                    </Accordion.Toggle>
                    <Accordion.Collapse eventKey="6">
                        <Card.Body>En cliquant sur « cela m’intéresse », vous figurerez comme « interessé à cet évènement » 
                        aux yeux des autres utilisateurs. Vos amis pourront voir que vous y participez, 
                        comme vous pourrez voir vos amis participer à des évènements.</Card.Body>
                    </Accordion.Collapse>
                </Card>
                <Card>
                    <Accordion.Toggle as={Card.Header} eventKey="7">
                    {filter === true ? 
                    <i className="bi bi-plus-square-fill me-2"></i> 
                    : <i className="bi bi-dash-square-fill me-2"></i>
                    }
                    JE SUIS CURIEUX/SE DE SAVOIR CE QU'IL SE PASSE AILLEURS QUE DANS MA VILLE
                    </Accordion.Toggle>
                    <Accordion.Collapse eventKey="7">
                        <Card.Body>Il vous suffit de taper le nom de la ville pour laquelle vous êtes intéressés de voir les évènements qui se passent 
                        ou les expériences à réserver dans la barre de recherche de notre application</Card.Body>
                    </Accordion.Collapse>
                </Card>
                </Accordion>
        <CardActivity />
        <Footer />
      </main>

      
    </div>
  )
}
