import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css';
import Banner from '../Components/Banner'
import CardActivity from '../Components/CardActivity'
import Carousel from '../Components/Carousel'
import Contact from '../Components/Contact'
import Footer from '../Components/Footer'

export default function Home() {
  return (
        <div>
            <Head>
                <title>Home - Community App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
        <main >
            <Banner />
            <Carousel />
            <div className="row mx-0 mb-5 mb-lg-2 align-items-center d-flex flex-column flex-lg-row">
                <div className="col col-lg-6 p-lg-5 d-none d-lg-block">
                    <Image className=""
                    src="/images/image1.jpg"
                    alt="boussole"
                    width={300}
                    height={200} 
                    layout="responsive"
                    />
                </div>
                <div className="col col-lg-6 text-center">
                    <h2 className={`${styles.title} mb-3 mb-lg-5`}>L’APPLICATION N°1 DES SORTIES <br/>ET ÉVÉNEMENTS EN FRANCE</h2>
                    <p className="px-5"> Un concept unique qui permet aux locaux et aux voyageurs de trouver rapidement des activités autour d’eux partout en France. 
                    <br /> COMMUNITY c'est plus de 380 000 événements mis à jour au quotidien !</p>
                    <button className={`${styles.bouton} btn btn-secondary mt-3`}>En savoir plus</button>
                </div>
            </div>
            <div className="row mx-0 mb-5 mb-lg-2 align-items-center d-flex flex-column flex-lg-row">
                <div className="col col-lg-6 text-center mb-5 mb-md-0">
                    <h2 className={`${styles.title} mb-3 mb-lg-5`}>VIVEZ DES MOMENTS UNIQUES <br/> AVEC NOS CHAPERONS</h2>
                    <p className="px-5">Sur l’app, venez découvrir des expériences uniques avec notre sélection d’experts locaux.
                    Partout où vous êtes, trouvez les évènements qui vous correspondent et partez à l’aventure !</p>
                    <button className={`${styles.bouton} btn btn-secondary mt-3`}>En savoir plus</button>
                </div>
                <div className="col col-lg-6 p-md-5">
                    <Image className=""
                    src="/images/image12.png"
                    alt="atelier chocolat"
                    width={1024}
                    height={855} 
                    layout="responsive"
                    />
                </div>
            </div>
            <div className="row m-0 align-items-center d-flex flex-column flex-lg-row">
                <div className="col col-lg-6 p-lg-5 d-none d-lg-block">
                    <Image className=""
                    src="/images/image2bis.png"
                    alt="Community App"
                    width={300}
                    height={300} 
                    layout="responsive"
                    />
                </div>
                <div className="col col-lg-6 p-md-5 mb-5">
                    <h2 className={`${styles.title} text-center mb-3 mb-md-5`}>LES AVIS DES " AVENTUREUX "</h2>
                    <div className="d-flex justify-content-start align-items-center">
                        <img src="/images/avatar2.png" width="40" height="40" className="me-3" alt="avatar"/>
                        <div>
                            <div className="text-center">Marianna</div>
                            <div><i className="bi bi-star-fill"></i><i className="bi bi-star-fill"></i><i className="bi bi-star-fill"></i><i className="bi bi-star-fill"></i><i className="bi bi-star-fill"></i></div>
                        </div>
                    </div>
                    <p className="mt-2">Cette app est idéale pour trouver des sorties, fêtes ou autres occupations à faire atour de soi quand on est en vacances ! Il y a beaucoup de choix et on peut regarder dans n’importe quelle ville de France avant d’y aller.</p>

                    <div className="d-flex justify-content-end align-items-center">
                        <div>
                            <div className="text-center">Laeticia</div>
                            <div><i className="bi bi-star-fill"></i><i className="bi bi-star-fill"></i><i className="bi bi-star-fill"></i><i className="bi bi-star-fill"></i><i className="bi bi-star-fill"></i></div>
                        </div>
                        <img src="/images/avatar2.png" width="40" height="40" className="ms-3" alt="avatar"/>
                    </div>
                    <p className="mt-2 text-end">Enfin un guide qui répertorie tout ce dont on a besoin… Que cela soit pour les visites, pour les vacances, les activités, les sorties, les hébergements ou toutes autres expériences… Hâte de devenir chaperon et de partir vers de nouvelles aventures !</p>

                    <div className="d-flex justify-content-start align-items-center">
                        <img src="/images/avatar2.png" width="40" height="40" className="me-3" alt="avatar"/>
                        <div>
                            <div className="text-center">Thomas</div>
                            <div><i className="bi bi-star-fill"></i><i className="bi bi-star-fill"></i><i className="bi bi-star-fill"></i><i className="bi bi-star-fill"></i><i className="bi bi-star-fill"></i></div>
                        </div>
                    </div>
                    <p className="mt-2"> Gros coup de coeur pour cette app ! Elle propose des activités autour de chez moi, je découvre de nouvelles expériences et des lieux inattendus dans ma ville. C’est vraiment simple, je peux suggérer des visites à des amis pour leurs vacances. Je recommande vivement pour les sorties.</p>
                </div>
            </div>
            <CardActivity />
            <Contact />
            <Footer />
        </main>
    </div>
  )
}
